services:
  - type: web
    name: dd-checker
    env: python
    buildCommand: |
      cd web_server
      apt-get update && apt-get install -y python3-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: cd web_server && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 